theme = "minimal"
baseurl = "/"
languageCode = "fr-FR"
title = "Et tout le touDIM"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "\\.Rproj"]


[permalinks]
    post = "/:year/:month/:day/:slug/"


[[menu.main]]
    name = "Accueil"
    url = "/"
    weight = 1


[[menu.main]]
    name = "Projets"
    url = "/projets/"
    weight = 3

[[menu.main]]
    name = "À propos"
    url = "/about/"
    weight = 4


[params]
    description = "Méthodes PMSI avec R"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"
    accent = "cornflowerblue"
    font = "Raleway" # should match the name on Google Fonts!
    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"


[[menu.icon]]
    url = "https://github.com/GuillaumePressiat/toudim/tree/master/public/methodes"
    name = "file-code-o"
    weight = 2

[[menu.icon]]
    url = "https://github.com/IM-APHP/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "http://guillaumepressiat.github.io/"
    name = "leaf"
    weight = 3
